sudo: required
services:
  -docker

before_install:
  - docker build -t hansryden/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hansryden/docker-react npm run test -- --coverage
